include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - bricks/**
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/generated_plugin_registrant.dart"

linter:
  rules:
