targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - swaggers2/**
      - input_folder/**
      - swagger_examples/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "input_folder/"
          output_folder: "lib/swagger_generated_code/"
          input_urls:
            - "https://shrouded-fortress-33438.herokuapp.com/openapi.json"
          # input_urls:
          #   - "http://localhost:3000/openapi.json"
          with_base_url: false
          with_converter: true
          separate_models: true
          enums_case_sensitive: false
          use_path_for_request_names: true
          use_default_null_for_lists: false
          override_equals_and_hashcode: true
          build_only_models: false
          additional_headers:
            - "Cache-Control"
          cut_from_model_names: "Dto"
          ignore_headers: false
          use_required_attribute_for_headers: false
          include_if_null: false