name: aswar
description: Advance architecture Hr Management system

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  
  cupertino_icons: ^1.0.2
  
  flutter_animate: ^1.0.0
  google_fonts: ^3.0.1


  logging: ^1.0.2
  extra_alignments: ^1.0.0+1
  flextras: ^0.0.2
  gap: ^2.0.0

  # client and error handling
  chopper: ^4.0.1
  error_handler: ^1.1.0

  bloc_error_handler:
    git: https://github.com/masreplay/bloc_error_handler.git

  # error handler
  auto_route: ^5.0.1

  # class and json serialization
  copy_with_extension: ^4.0.3
  json_annotation: ^4.4.0

  # state management
  provider: ^6.0.3
  injectable: ^1.5.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

  # app shape
  flutter_intro_screen: ^0.0.4
  flutter_launcher_icons: ^0.10.0
  font_awesome_flutter: ^10.2.1
  flutter_native_splash: ^2.2.9
  url_launcher: ^6.1.5

  # local storage
  shared_preferences: ^2.0.15

  device_preview: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  chopper_generator: ^4.0.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  auto_route_generator: ^5.0.1
  injectable_generator: ^1.5.4
  copy_with_extension_gen: ^4.0.3
  swagger_dart_code_generator: ^2.4.6

flutter:
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  uses-material-design: true
