name: aswar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^5.0.1
  chopper: ^4.0.1
  cupertino_icons: ^1.0.2
  error_handler: # ^1.0.5
    path: ../perfect_error_handler
    # git: https://github.com/masreplay/perfect_error_handler.git

  extra_alignments: ^1.0.0+1
  flextras: ^0.0.2
  flutter_animate: ^1.0.0
  flutter_intro_screen: ^0.0.4
  flutter_svg: ^1.1.5
  gap: ^2.0.0
  json_annotation: ^4.4.0
  provider: ^6.0.3
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^3.0.1
  injectable: ^1.5.3
  get_it: ^7.2.0
  intl: ^0.17.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9
  shared_preferences: ^2.0.15
  flutter_riverpod: ^1.0.4
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.7
  chopper_generator: ^4.0.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  auto_route_generator: ^5.0.1
  injectable_generator: ^1.5.4
  swagger_dart_code_generator: ^2.4.6

flutter:
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  uses-material-design: true
