name: aswar
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  chopper: ^4.0.1
  cupertino_icons: ^1.0.2
  error_handler:
    git: https://github.com/masreplay/perfect_error_handler.git
  extra_alignments: ^1.0.0+1
  flextras: ^0.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.5
  gap: ^2.0.0
  json_annotation: ^4.4.0
  provider: ^6.0.3
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.1.7
  chopper_generator: ^4.0.5

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  swagger_dart_code_generator: ^2.4.6

flutter:
  generate: true
  uses-material-design: true
